//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.products = new HashSet<products>();
        }
    
        public int categoryid { get; set; }
        public string categoryname { get; set; }
        public string categorydescription { get; set; }
        public Nullable<int> superiorcategoryid { get; set; }
        public byte[] timestamp_column { get; set; }
    
        public virtual ICollection<products> products { get; set; }
    }
}
