//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public customers()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int customerid { get; set; }
        public string customername { get; set; }
        public string address { get; set; }
        public string contactperson { get; set; }
        public string phone { get; set; }
        public string phonetype { get; set; }
        public string email { get; set; }
        public string skypename { get; set; }
        public string url { get; set; }
    
        public virtual ICollection<orders> orders { get; set; }
    }
}
