//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaEntities : DbContext
    {
        public PizzaEntities()
            : base("name=PizzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<orderdetails> orderdetails { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orderssecurity> orderssecurity { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<vfxaudit> vfxaudit { get; set; }
        public virtual DbSet<vfxauditedtables> vfxauditedtables { get; set; }
        public virtual DbSet<vfxdocuments> vfxdocuments { get; set; }
        public virtual DbSet<vfxfilter> vfxfilter { get; set; }
        public virtual DbSet<vfxfopen> vfxfopen { get; set; }
        public virtual DbSet<vfxgrouprights> vfxgrouprights { get; set; }
        public virtual DbSet<vfxgroups> vfxgroups { get; set; }
        public virtual DbSet<vfxipaddresses> vfxipaddresses { get; set; }
        public virtual DbSet<vfxlock> vfxlock { get; set; }
        public virtual DbSet<vfxlog> vfxlog { get; set; }
        public virtual DbSet<vfxloggedusers> vfxloggedusers { get; set; }
        public virtual DbSet<vfxpdef> vfxpdef { get; set; }
        public virtual DbSet<vfxqueries> vfxqueries { get; set; }
        public virtual DbSet<vfxreports> vfxreports { get; set; }
        public virtual DbSet<vfxres> vfxres { get; set; }
        public virtual DbSet<vfxrtf> vfxrtf { get; set; }
        public virtual DbSet<vfxsdef> vfxsdef { get; set; }
        public virtual DbSet<vfxsys> vfxsys { get; set; }
        public virtual DbSet<vfxsysid> vfxsysid { get; set; }
        public virtual DbSet<vfxtasklist> vfxtasklist { get; set; }
        public virtual DbSet<vfxtaskliststatus> vfxtaskliststatus { get; set; }
        public virtual DbSet<vfxtipoftheday> vfxtipoftheday { get; set; }
        public virtual DbSet<vfxtoolbox> vfxtoolbox { get; set; }
        public virtual DbSet<vfxtooltype> vfxtooltype { get; set; }
        public virtual DbSet<vfxusergroups> vfxusergroups { get; set; }
        public virtual DbSet<vfxuserlog> vfxuserlog { get; set; }
        public virtual DbSet<vfxusr> vfxusr { get; set; }
        public virtual DbSet<vfxplist> vfxplist { get; set; }
        public virtual DbSet<vfxrep> vfxrep { get; set; }
        public virtual DbSet<vfxrtemp> vfxrtemp { get; set; }
        public virtual DbSet<vfxrtype> vfxrtype { get; set; }
    }
}
