//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxaudit
    {
        public string table { get; set; }
        public string recordid { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string changes { get; set; }
        public int idvfxaudit { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
