//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxdocuments
    {
        public int docid { get; set; }
        public string filename { get; set; }
        public string filedirect { get; set; }
        public Nullable<int> parentkey { get; set; }
        public string filedescr { get; set; }
        public string parenttbl { get; set; }
        public Nullable<int> rtfid { get; set; }
        public Nullable<decimal> doctype { get; set; }
        public string entryid { get; set; }
    }
}
