//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxfilter
    {
        public string user { get; set; }
        public string objname { get; set; }
        public string index { get; set; }
        public Nullable<bool> descending { get; set; }
        public string layout { get; set; }
        public Nullable<decimal> page { get; set; }
        public Nullable<bool> toolbar { get; set; }
        public int idvfxfiltr { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
