//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxfopen
    {
        public string objectid { get; set; }
        public Nullable<decimal> objectno { get; set; }
        public string groupcap { get; set; }
        public string title { get; set; }
        public string descr { get; set; }
        public string form { get; set; }
        public string parameter { get; set; }
        public Nullable<decimal> viewlevel { get; set; }
        public Nullable<decimal> newlevel { get; set; }
        public Nullable<decimal> copylevel { get; set; }
        public Nullable<decimal> editlevel { get; set; }
        public Nullable<decimal> printlevel { get; set; }
        public Nullable<decimal> inetlevel { get; set; }
        public Nullable<decimal> eraselevel { get; set; }
        public Nullable<bool> favorites { get; set; }
        public string primarykey { get; set; }
        public string favordescr { get; set; }
        public Nullable<decimal> explevel { get; set; }
        public Nullable<decimal> filtrlevel { get; set; }
        public string iconfile { get; set; }
        public Nullable<bool> notvisible { get; set; }
        public Nullable<decimal> tbrcbosort { get; set; }
        public Nullable<decimal> parentno { get; set; }
        public string keybkey { get; set; }
        public string allowedfor { get; set; }
        public int idvfxfopen { get; set; }
        public string xapname { get; set; }
        public Nullable<decimal> auditlevel { get; set; }
        public Nullable<bool> largeicon { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
