//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxgroups
    {
        public int groupid { get; set; }
        public string groupdescr { get; set; }
        public Nullable<decimal> fltrpermit { get; set; }
        public Nullable<decimal> mreppermit { get; set; }
    }
}
