//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxgrouprights
    {
        public Nullable<int> groupid { get; set; }
        public string formname { get; set; }
        public Nullable<decimal> viewpermit { get; set; }
        public Nullable<decimal> inspermit { get; set; }
        public Nullable<decimal> editpermit { get; set; }
        public Nullable<decimal> delpermit { get; set; }
        public Nullable<decimal> prtpermit { get; set; }
        public Nullable<decimal> copypermit { get; set; }
        public Nullable<decimal> exppermit { get; set; }
        public Nullable<decimal> fltrpermit { get; set; }
        public string objectid { get; set; }
        public Nullable<decimal> objectno { get; set; }
        public int idvfxgrrgh { get; set; }
        public Nullable<int> idvfxfopen { get; set; }
    }
}
