//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxlock
    {
        public string table { get; set; }
        public Nullable<decimal> record { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
        public string user_name { get; set; }
        public int idvfxlock { get; set; }
    }
}
