//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxloggedusers
    {
        public string user { get; set; }
        public string networkmi { get; set; }
        public string ipaddress { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public string datadir { get; set; }
        public Nullable<int> spid { get; set; }
        public int idvfxlogur { get; set; }
        public Nullable<int> idvfxusr { get; set; }
    }
}
