//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxlog
    {
        public string type { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
        public Nullable<decimal> error { get; set; }
        public string message { get; set; }
        public string method { get; set; }
        public string tables { get; set; }
        public string code { get; set; }
        public string memory { get; set; }
        public string status { get; set; }
        public int idvfxlog { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
