//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxpdef
    {
        public int parentid { get; set; }
        public string code { get; set; }
        public string descript { get; set; }
        public Nullable<decimal> fieldlen { get; set; }
        public Nullable<bool> ltextkey { get; set; }
        public Nullable<bool> caninsert { get; set; }
        public Nullable<bool> askforsave { get; set; }
        public Nullable<decimal> newlevel { get; set; }
        public Nullable<decimal> columncnt { get; set; }
        public Nullable<decimal> combostyle { get; set; }
        public string proccode { get; set; }
        public Nullable<bool> autogcode { get; set; }
        public Nullable<bool> useidfield { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
