//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxplist
    {
        public string picklist { get; set; }
        public string code { get; set; }
        public string descript { get; set; }
        public Nullable<bool> active { get; set; }
        public string value { get; set; }
        public string proccode { get; set; }
        public int idvfxplist { get; set; }
        public Nullable<int> parentid { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
