//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxqueries
    {
        public string querytitle { get; set; }
        public string descript { get; set; }
        public string selectcmd { get; set; }
        public string colwidth { get; set; }
        public string fieldtitle { get; set; }
        public string whereclaus { get; set; }
        public string orderclaus { get; set; }
        public string crsresult { get; set; }
        public Nullable<decimal> userlevel { get; set; }
        public string useraccess { get; set; }
        public Nullable<bool> active { get; set; }
        public int vfxqueryid { get; set; }
        public Nullable<bool> caquery { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
