//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxrep
    {
        public int reportid { get; set; }
        public Nullable<int> rtypeid { get; set; }
        public string filename { get; set; }
        public string descr { get; set; }
        public string user { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
