//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxrtf
    {
        public int rtfid { get; set; }
        public string rtftext { get; set; }
        public string parenttbl { get; set; }
        public Nullable<int> parentid { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
