//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxreports
    {
        public int repid { get; set; }
        public string repuser { get; set; }
        public string repform { get; set; }
        public string repfile { get; set; }
        public string repcaption { get; set; }
        public string repdesc { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
