//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxsdef
    {
        public string ftpurl { get; set; }
        public Nullable<int> ftpport { get; set; }
        public string ftpupini { get; set; }
        public string ftpdwnini { get; set; }
        public string ftpupdata { get; set; }
        public string ftpdwndata { get; set; }
        public string ftpupconf { get; set; }
        public string ftpdwnconf { get; set; }
        public string ftpuser { get; set; }
        public string ftppass { get; set; }
        public string version { get; set; }
        public string code { get; set; }
        public string machine { get; set; }
        public string profile { get; set; }
        public Nullable<bool> up_load { get; set; }
        public Nullable<bool> dn_load { get; set; }
        public Nullable<bool> use_boss { get; set; }
        public Nullable<System.DateTime> last_conn { get; set; }
        public Nullable<System.DateTime> last_up { get; set; }
        public Nullable<System.DateTime> last_dn { get; set; }
        public int idvfxsdef { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
