//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxsys
    {
        public string magic_id { get; set; }
        public string install_gs { get; set; }
        public string dunconnpar { get; set; }
        public string updateapp { get; set; }
        public string archpath { get; set; }
        public string install_ar { get; set; }
        public string dyndns { get; set; }
        public string inst_click { get; set; }
        public string appversion { get; set; }
        public Nullable<System.DateTime> lastcheckd { get; set; }
        public Nullable<int> updtype { get; set; }
        public string customize { get; set; }
        public Nullable<int> autologin { get; set; }
        public Nullable<System.DateTime> lastsync { get; set; }
        public string install_fc { get; set; }
        public string install_lh { get; set; }
        public int idvfxsys { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
