//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxtoolbox
    {
        public string uniqueid { get; set; }
        public string showtype { get; set; }
        public string tooltypeid { get; set; }
        public string tooltype { get; set; }
        public string parentid { get; set; }
        public string toolname { get; set; }
        public string imagefile { get; set; }
        public string classtype { get; set; }
        public string setid { get; set; }
        public string classname { get; set; }
        public string classlib { get; set; }
        public string tooltip { get; set; }
        public string helpfile { get; set; }
        public Nullable<decimal> helpid { get; set; }
        public string tooldata { get; set; }
        public Nullable<int> displayord { get; set; }
        public Nullable<bool> lockadd { get; set; }
        public Nullable<bool> lockdelete { get; set; }
        public Nullable<bool> lockrename { get; set; }
        public Nullable<bool> inactive { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public int idvfxtbox { get; set; }
        public Nullable<int> idvfxttype { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
