//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxtasklist
    {
        public int idtasklist { get; set; }
        public string descr { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<int> status { get; set; }
        public string form { get; set; }
        public string idkeyfield { get; set; }
        public string formdescr { get; set; }
        public Nullable<decimal> assnum { get; set; }
        public Nullable<int> groupid { get; set; }
        public string user { get; set; }
        public string icon { get; set; }
        public Nullable<int> ins_usr { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public Nullable<int> edt_usr { get; set; }
        public Nullable<System.DateTime> edt_date { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
