//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxtooltype
    {
        public string uniqueid { get; set; }
        public string showtype { get; set; }
        public string tooltype { get; set; }
        public string classname { get; set; }
        public string classlib { get; set; }
        public string filetype { get; set; }
        public string datavalues { get; set; }
        public Nullable<bool> shownew { get; set; }
        public Nullable<bool> propsheet { get; set; }
        public string defaultid { get; set; }
        public Nullable<int> displayord { get; set; }
        public string tooltip { get; set; }
        public Nullable<bool> inactive { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public int idvfxttype { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
