//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxusr
    {
        public string user { get; set; }
        public string password { get; set; }
        public string user_name { get; set; }
        public Nullable<decimal> userlevel { get; set; }
        public string useraccess { get; set; }
        public Nullable<decimal> firstview { get; set; }
        public string lastsel { get; set; }
        public Nullable<decimal> formsize { get; set; }
        public Nullable<bool> agent { get; set; }
        public string favorites { get; set; }
        public Nullable<decimal> lastfile { get; set; }
        public string email { get; set; }
        public Nullable<decimal> chpassall { get; set; }
        public Nullable<decimal> chpassnext { get; set; }
        public string language { get; set; }
        public Nullable<bool> allusrcust { get; set; }
        public Nullable<bool> mulusrlog { get; set; }
        public Nullable<decimal> fltrpermit { get; set; }
        public Nullable<decimal> mreppermit { get; set; }
        public int idvfxusr { get; set; }
        public string ntlogon { get; set; }
        public Nullable<bool> strongpass { get; set; }
        public Nullable<bool> uniquepass { get; set; }
        public Nullable<System.DateTime> passexpiry { get; set; }
        public string histrypass { get; set; }
        public Nullable<bool> notactive { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
