//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vfxusergroups
    {
        public Nullable<int> groupid { get; set; }
        public string user { get; set; }
        public int idvfxusrgr { get; set; }
        public int idvfxusr { get; set; }
    }
}
